### ISSUE TITLE
Installation Manual updates

### ISSUE THREAD

**Issue by rbartelme** [jiabowang/GAPIT3#10]
The installation manual needs updating with BiocManager installation of multtest `BiocManager::install("multtest")` for R 3.6+. The dependency snpStats for LDheatmap is missing as well, which is installed via `BiocManager::install("snpStats")`.  Without snpStats LDheatmap will have a non-zero exit status.

**Comment by jiabowang** [comment]
Thanks a lot.

**Comment by jguhlin** [comment]
Same problem. Perhaps you could list which version of R you are developing GAPIT for? I'm going to try R4.0 and see if that works.

**Comment by billzt** [comment]
@jguhlin 
```
$ wget https://cran.r-project.org/src/contrib/Archive/LDheatmap/LDheatmap_0.99-8.tar.gz
$ R
> install.packages("/your/path/LDheatmap_0.99-8.tar.gz", repos=NULL, type="source")
```
