### ISSUE TITLE
"There are  1  traits in phenotype data."

### ISSUE THREAD

**Issue by jeremysutherland** [jiabowang/GAPIT3#12]
[1] "--------------------Phenotype and Genotype ----------------------------------"
[1] "Blink"
**[1] "There are  1  traits in phenotype data."**
[1] "There are  292  individuals in phenotype data."
[1] "There are  1878584  markers in genotype data."
[1] "Phenotype and Genotype are test OK !!"
[1] "--------------------GAPIT Logical ----------------------------------"
[1] "GAPIT.IC in process..."
[1] 263   4
[1] "GAPIT.IC accomplished successfully for multiple traits. Results are saved"
[1] "GAPIT.SS in process..."
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1, 0
In addition: There were 17 warnings (use warnings() to see them)

-----
Except my phenotype data has more than 200 traits (microbiome taxa in this case)
 Y <-  read.table("pheno.txt", head = TRUE, sep = "\t")
dim(Y)
[1] 292 231

How can I fix this issue? I'm also unsure what "arguments imply differing number of rows: 1, 0" but I'm assuming it has to do with my phenotype data not being read in correctly?

Thanks!

**Comment by YvelinePailles** [comment]
Hi. I have the same problem. Did you find a solution?

**Comment by jeremysutherland** [comment]
I did not. I ended up going with another program, GWASpoly.

**Comment by YvelinePailles** [comment]
Thanks! I found that the Taxa names in my genotype file were not the same as the ones in the phenotypes file, after correcting them, the script is running past the point of that error.

**Comment by wellionx** [comment]
I had the same problem, but I found its my fault to read genotype with header = TRUE, you have to do as the manual, set header = FALSE, so that GAPIT can recognize you Taxa names from the first row, I guss.

**Comment by Roopali87** [comment]
Hi, I am running GAPIT and checked both the files for accurate names but the following error is appearing\Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1, 0
In addition: Warning message:
In base::order(..., na.last = na.last, decreasing = decreasing) :
  NAs introduced by coercion

Can you please help me fox this.

**Comment by mdkrause** [comment]
@wellionx, that is correct. You should use header = FALSE. Just keep in mind the chromosome number must be numeric, i.e. if 1 is written as 01 (given header = FALSE), GAPIT will crash.

**Comment by jkitony** [comment]
"Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 1, 0"
Ensure your phenotype data is space delimited
