### ISSUE TITLE
possible Manhattan plot FDR threshold bug

### ISSUE THREAD

**Issue by AlexCalderwood** [jiabowang/GAPIT3#13]
Hi, 
Thanks a lot for the nice library. I think there might be an error in the calculation of FDRcutoff at line 76 of GAPIT.Manhattan.R. 

My understanding is that the plotted threshold is intended to be the Benjamini-Hochberg corrected threshold, but the equation as written doesn't seem to be consistent with Eqn 1 of the BH 1995 paper.

In my hands, this results in too lenient a threshold being plotted, showing significant values which are inconsistent with the significant values output in the FDR_Adjusted_P-values column output in the XXX.GWAS.Results.csv file.  

Hopefully I'm wrong - otherwise I lose a lot of "significant" peaks :)

**Comment by jiabowang** [comment]
Hi,

The BH method adjusted P-value actually is ordered the P-value and denoted by Bonferroni procedure. The Eqn 1 is the Bonferroni procedure. So the BH adjusted should be lenient to the Bonferroni cutoff.

**Comment by AlexCalderwood** [comment]
Thanks for your reply

I agree that BH should be lenient compared to the Bonferroni cutoff. 
But aren't both the output Manhatten plot significance threshold, and the FDR_Adjusted_P-values in the output GWAS.Results.csv file meant to be BH adjusted?

In the Manhatten plot many points are plotted above the significance threshold.

[GAPIT.Blink.height.Manhattan.Plot.Genomewise.pdf](https://github.com/jiabowang/GAPIT3/files/5451193/GAPIT.Blink.height.Manhattan.Plot.Genomewise.pdf)

However, in the GWAS.Results.csv file, generated from the same data in the FDR_Adjusted_P-values column, no rows are significant. The smallest value is 0.723677456. 

I believe that H0 rejecting values under BH should be for those p-values for which the inequality in eqn 1 is true, but this doesn't seem to be how the threshold is calculated @ line 76

**Comment by jiabowang** [comment]
Yes, you are right.
We have fixed this error.
Thank you very much.
