### ISSUE TITLE
GAPIT installation error

### ISSUE THREAD

**Issue by sekhwal** [jiabowang/GAPIT3#15]
Hi,
I am trying to install GAPIT using following commands. However, I am getting errors.

install.packages("devtools")
devtools::install_github("jiabowang/GAPIT3")
library(GAPIT3)

Here is the complete error message:

Skipping 1 packages not available: multtest

* installing *source* package 'GAPIT3' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'multtest::wapply' by 'gplots::wapply' when loading 'GAPIT3'
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'ape'
Installing package into 'E:/R/R-4.0.4/library/00LOCK-GAPIT3/00new'
(as 'lib' is unspecified)
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Error: unable to load R code in package 'GAPIT3'
Execution halted
ERROR: lazy loading failed for package 'GAPIT3'
* removing 'E:/R/R-4.0.4/library/GAPIT3'

Error: Failed to install 'GAPIT3' from GitHub:
  (converted from warning) installation of package ‘C:/Users/AppData/Local/Temp/Rtmp69Xt8w/file192c2c9c5ec7/GAPIT3_3.1.0.tar.gz’ had non-zero exit status

**Comment by kaadeboye** [comment]
Hello, are you able to solve this problem? Please share how you solved it.

**Comment by 9437951970** [comment]
I am trying to istall using this command.
remotes::install_github('jiabowang/GAPIT')

These are the errors, I am getting-
Downloading GitHub repo jiabowang/GAPIT@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: rlang    (1.1.1 -> 1.1.2) [CRAN]
5: cli      (3.5.0 -> 3.6.1) [CRAN]
6: curl     (4.3.2 -> 5.1.0) [CRAN]
7: processx (3.8.1 -> 3.8.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
── R CMD build ───────────────────────────────────────────────────────────────────────────
Error: Failed to install 'GAPIT' from GitHub:Local\Temp\RtmpC8zcAd\remotes2c784a937787\jiabowang-GAPIT-2d8d50a/DESCRIPTION' ... 
  lazy-load database 'C:/Users/Ashis/AppData/Local/R/win-library/4.2/prettyunits/R/prettyunits.rdb' is corrupt
In addition: Warning messages:
1: In paste0(" (", pretty_dt(elapsed), ")") :
  restarting interrupted promise evaluation
2: In paste0(" (", pretty_dt(elapsed), ")") :
  internal error -3 in R_decompress1

**Comment by swansong499** [comment]
How do I solve this issue with installation of GAPIT3 

devtools::install_github("jiabowang/GAPIT3",force=TRUE)
Downloading GitHub repo jiabowang/GAPIT3@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                            
2: CRAN packages only             
3: None                           
4: rlang   (1.1.3 -> 1.1.4) [CRAN]
5: fastmap (1.1.1 -> 1.2.0) [CRAN]
6: fs      (1.6.3 -> 1.6.4) [CRAN]
7: cachem  (1.0.8 -> 1.1.0) [CRAN]
8: stringi (1.8.3 -> 1.8.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
rlang   (1.1.3 -> 1.1.4) [CRAN]
fastmap (1.1.1 -> 1.2.0) [CRAN]
fs      (1.6.3 -> 1.6.4) [CRAN]
cachem  (1.0.8 -> 1.1.0) [CRAN]
stringi (1.8.3 -> 1.8.4) [CRAN]
Skipping 3 packages ahead of CRAN: BiocGenerics, Biobase, multtest
Installing 5 packages: rlang, fastmap, fs, cachem, stringi
Installing packages into ‘C:/Users/Yadavr/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://bioconductor.org/packages/3.17/data/annotation/bin/windows/contrib/4.3:
  cannot open URL 'https://bioconductor.org/packages/3.17/data/annotation/bin/windows/contrib/4.3/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.17/data/experiment/bin/windows/contrib/4.3:
  cannot open URL 'https://bioconductor.org/packages/3.17/data/experiment/bin/windows/contrib/4.3/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.17/workflows/bin/windows/contrib/4.3:
  cannot open URL 'https://bioconductor.org/packages/3.17/workflows/bin/windows/contrib/4.3/PACKAGES'
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/rlang_1.1.4.zip'
Content type 'application/zip' length 1581093 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/fastmap_1.2.0.zip'
Content type 'application/zip' length 133255 bytes (130 KB)
downloaded 130 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/fs_1.6.4.zip'
Content type 'application/zip' length 408764 bytes (399 KB)
downloaded 399 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/cachem_1.1.0.zip'
Content type 'application/zip' length 72520 bytes (70 KB)
downloaded 70 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/stringi_1.8.4.zip'
Content type 'application/zip' length 14997376 bytes (14.3 MB)
downloaded 14.3 MB

package ‘rlang’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘rlang’
Warning: restored ‘rlang’
package ‘fastmap’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘fastmap’
Warning: restored ‘fastmap’
package ‘fs’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘fs’
Warning: restored ‘fs’
package ‘cachem’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘cachem’
Warning: restored ‘cachem’
package ‘stringi’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘stringi’
Warning: restored ‘stringi’

The downloaded binary packages are in
	C:\Users\Yadavr\AppData\Local\Temp\RtmpaOpVLv\downloaded_packages
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\Yadavr\AppData\Local\Temp\RtmpaOpVLv\remotes7724594917ef\jiabowang-GAPIT-2b1110f/DESCRIPTION' (489ms)
─  preparing 'GAPIT': (373ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'GAPIT_3.4.0.tar.gz'
   
Installing package into ‘C:/Users/Yadavr/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
* installing *source* package 'GAPIT' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Note: break used in wrong context: no loop is visible 
Note: possible error in 'GAPIT(Y = Y, CV = CV, ': unused argument (GTindex = GTindex) 
Note: possible error in 'layout(title = "Interactive.Manhattan.Plot", ': unused arguments (title = "Interactive.Manhattan.Plot", xaxis = list(title = "Chromsome", zeroline = FALSE, showticklabels = FALSE), yaxis = list(title = "-Log10(p)")) 
Note: possible error in 'layout(title = "Interactive.Multiple_Synthesis.Manhattan.Plot", ': unused arguments (title = "Interactive.Multiple_Synthesis.Manhattan.Plot", xaxis = list(title = "Chromsome", zeroline = FALSE, showticklabels = FALSE), yaxis = list(title = "-Log10(p)")) 
Note: possible error in 'layout(title = "Interactive.Multiple_Synthesis.Manhattan.Plot", ': unused arguments (title = "Interactive.Multiple_Synthesis.Manhattan.Plot", xaxis = list(title = "Chromsome", zeroline = FALSE, showticklabels = FALSE), yaxis = list(title = "-Log10(p)")) 
Note: possible error in 'GAPIT(Y = myY, GD = myGD, ': unused arguments (threshold.output = 0.001, iteration.output = TRUE) 
Note: possible error in 'GAPIT(Y = myY, GD = myGD, ': unused arguments (threshold.output = 0.001, iteration.output = TRUE) 
Note: possible error in 'GAPIT(Y = myY, GD = myGD, ': unused arguments (LD = 0.1, threshold.output = 0.001, iteration.output = TRUE) 
Note: possible error in 'GAPIT(Y = myY, GD = myGD, ': unused arguments (threshold.output = 0.001, iteration.output = TRUE) 
Note: possible error in 'GAPIT(Y = myY, G = myG, ': unused arguments (threshold.output = 0.001, iteration.output = TRUE) 
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (GAPIT)
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Yadavr\AppData\Local\R\win-library\4.3\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\Yadavr\AppData\Local\R\win-library\4.3\rlang\libs\x64\rlang.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Yadavr\AppData\Local\R\win-library\4.3\00LOCK\fastmap\libs\x64\fastmap.dll to C:\Users\Yadavr\AppData\Local\R\win-library\4.3\fastmap\libs\x64\fastmap.dll: Permission denied
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Yadavr\AppData\Local\R\win-library\4.3\00LOCK\fs\libs\x64\fs.dll to C:\Users\Yadavr\AppData\Local\R\win-library\4.3\fs\libs\x64\fs.dll: Permission denied
4: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Yadavr\AppData\Local\R\win-library\4.3\00LOCK\cachem\libs\x64\cachem.dll to C:\Users\Yadavr\AppData\Local\R\win-library\4.3\cachem\libs\x64\cachem.dll: Permission denied
5: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Yadavr\AppData\Local\R\win-library\4.3\00LOCK\stringi\libs\icudt74l.dat to C:\Users\Yadavr\AppData\Local\R\win-library\4.3\stringi\libs\icudt74l.dat: Invalid argument
6: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Yadavr\AppData\Local\R\win-library\4.3\00LOCK\stringi\libs\x64\stringi.dll to C:\Users\Yadavr\AppData\Local\R\win-library\4.3\stringi\libs\x64\stringi.dll: Permission denied
library(GAPIT3)
Error in library(GAPIT3) : there is no package called ‘GAPIT3’
