### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sekhwal** [jiabowang/GAPIT3#16]
source("http://www.zzlab.net/GAPIT/GAPIT.library.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  InternetOpenUrl failed: 'A connection with the server could not be established'

**Comment by kaadeboye** [comment]
Hello, are you able to resolve this? I am having these same issue. Please share how you solved it. Regards.

**Comment by sekhwal** [comment]
Hi,
I got the following response from the developer for this issue, which helped me but eventually I did not go with GAPIT for my analysis. However, it might help you.
-------------
The possible cause could be the functions were not be imported to your R environment yet. Please import those functions first as following:
source("http://www.zzlab.net/GAPIT/GAPIT.library.R")
source("http://www.zzlab.net/GAPIT/gapit_functions.txt")
source("http://www.zzlab.net/FarmCPU/FarmCPU_functions.txt")
source("http://www.zzlab.net/GAPIT/emma.txt")

**Comment by kaadeboye** [comment]
Thank you. I have used this and the same issue persists. What's the alternative?

**Comment by sekhwal** [comment]
Did you try these all packages. If you already tried, I would recommend to re-install these. If it still exists you may contact developer or generate the issue at GAPIT google group page (https://groups.google.com/g/gapit-forum?pli=1).

----------Contact------

Website (Personal): http://css.wsu.edu/zhiwu-zhang
Website (Lab): https://zzlab.net
Email: Zhiwu.Zhang@wsu.edu

-------------------------------Packages------
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
library("BiocManager")

BiocManager::install("multtest")

library(multtest)
#install.packages("multtest")

BiocManager::install("gplots")
library("gplots")

BiocManager::install("LDheatmap")
library("LDheatmap")

BiocManager::install("genetics")
library("genetics")

BiocManager::install("EMMREML")
library("EMMREML")

library("compiler")

install.packages("devtools")
devtools::install_github("jiabowang/GAPIT3",force=TRUE)
library(GAPIT3)

**Comment by kaadeboye** [comment]
I will try this and revert. Thank you very much.

**Comment by knausb** [comment]
I concur with https://github.com/jiabowang/GAPIT3/issues/16#issuecomment-856969730 . I used the following (devtools already installed).

```
devtools::install_github("jiabowang/GAPIT3",force=TRUE)
library(GAPIT3)
```

And everything appears fine.

**Comment by kaadeboye** [comment]
Thank you very much. I have been able to install successfully.

**Comment by chailixuan** [comment]
the answer is silly... 

source("http://www.zzlab.net/GAPIT/gapit_functions.txt")
source("http://zzlab.net/GAPIT/gapit_functions.txt")

see the two command different?
yes...   www. just delete these...

the gapit_document should be resposible for this error...

**Comment by chailixuan** [comment]
Yes!Thanks a lot! But i find some mistakes in the gapit_help_document like that.
Please fix those...

**Comment by tesfay1981** [comment]
I am getting this error while trying to install In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘LDheatmap’

**Comment by jiabowang** [comment]
The function in GitHub has removed the LDheatmap package. Please source the new GAPIT function or re-install it from GitHub.
