### ISSUE TITLE
erro in myGD3[, w1_start:w1_end] : subscript out of bounds 

### ISSUE THREAD

**Issue by Dkyuan** [jiabowang/GAPIT3#18]
@jiabowang 
Dear Dr.  Wang:

When performing association with variations in a regon, it reported  an erro in myGD3[, w1_start:w1_end] : subscript out of bounds after Kinship created. (The variation number is 3248, GAPIT version is 2020.10.24, GAPIT 3.0)

Details:
[1] "Kinship save as file"
[1] "Kinship created!"
Error in myGD3[, w1_start:w1_end] : subscript out of bounds
Calls: GAPIT -> GAPIT.DP -> GAPIT.Genotype -> GAPIT.Genotype.View

It seems sth wrong with the genotype, as association with variations in another region was normal. (The variation number is  2657)
But I don't known what was wrong. Could you help me to deal with it?  Attached is the genotype file.

Another question is that: How could I turn off some functions while performing GWAS, such as GAPIT.Genotype.View and phenotype view function? Files of phenotype_view.pdf and MAF.pdf were repeatly generated in different models.

[for_GWAS_region_03.merged.hmp.txt](https://github.com/jiabowang/GAPIT3/files/6708451/for_GWAS_region_03.merged.hmp.txt)

Thanks!

Best wishes !

**Comment by jiabowang** [comment]
Hi,

Could you check how many markers are in your first Chromosome?
If you want skip this error, please add the code:Geno.View.output=FALSE

xuan ***@***.***> 于2021年6月24日周四 下午6:32写道：
