### ISSUE TITLE
Blink single covariate issue

### ISSUE THREAD

**Issue by jlboat** [jiabowang/GAPIT3#19]
Hello,

I'm getting the following error from running the BLINK model in GAPIT with one covariate that may also affect other model functions but doesn't seem to affect MLM. Someone else also mentioned this error here (https://www.biostars.org/p/412603/), but it was considered off topic.

Error in if (ncol(CV) == 1) { : argument is of length zero
Calls: GAPIT -> GAPIT.SS -> GAPIT.Bus -> Blink

The cause of this error appears to originate in line 1,748 of gapit_functions.txt where the following command is used:
if(!is.null(CV))blink_CV=CV[,-1]

Normally this is fine. However, when using a single covariate data frame, this results in a numeric vector rather than a data frame. I recommend changing this line to:

if(!is.null(CV))blink_CV=CV[,-1, drop=FALSE]

If you search for ",-1]" you will find similar potential issues (ex. line 1,174, etc). This shouldn't be an issue for things like KI or GD, but it might not hurt to change those instances as well.

Of course, even after that fix I had another error:

Error in `[.data.frame`(CV, seqTaxa) : undefined columns selected
Calls: GAPIT ... GAPIT.SS -> GAPIT.Bus -> Blink -> [ -> [.data.frame

The traceback is as follows:
Error in `[.data.frame`(CV, seqTaxa) : undefined columns selected
In addition: There were 15 warnings (use warnings() to see them)
> traceback()  # partial
      11: stop("undefined columns selected")
      10: `[.data.frame`(CV, seqTaxa) at gapit_functions.txt#161
      9: CV[seqTaxa] at gapit_functions.txt#161

This was resolved by editing (line 161 or so):
    if(!is.null(CV)){
      if(ncol(CV)==1){
        CV1=CV[seqTaxa]
      }else{
        CV1=CV[seqTaxa,]
      }

To:
    if(!is.null(CV)){
        CV1=CV[seqTaxa,]
      }

Because now it's a data frame and you don't need a check for both vector and data frame.

My locally edited version now appears to run just fine.

**Comment by jiabowang** [comment]
Thank you very much for your detailed explanation and suggestion.
We will follow your comments to address our code.
Thanks again.
