### ISSUE TITLE
Multi-model analysis: FarmCPU and GLM results are identical

### ISSUE THREAD

**Issue by fmobegi** [jiabowang/GAPIT3#20]
When running multiple models under one command, if FarmCPU goes before GLM in the list of models, the GLM results are identical to farmCPU. However, when you reverse the order, the results are different as one would expect. 

here is my example:
```
pacman::p_load(GAPIT3, data.table)

setwd("mywd")

myY <- read.delim("pheno.txt", header = TRUE, check.names = F, stringsAsFactors = F)
myG <- fread("genotype.tsv", check.names = FALSE, header = FALSE, nThread = 8, sep = "\t")

myG[1:4, 1:5]
head(myY)

#Step 2: Run GAPIT
myGAPIT <- GAPIT(
  Y=myY,
  G=myG,
  PCA.total=3,
  model=c("MLM", "FarmCPU", "GLM", "Blink", "SUPER"),
  Multiple_analysis=TRUE,
  file.output=T)
```
And the manhattan I combined from the analysis:

![image](https://user-images.githubusercontent.com/16131975/127263575-36e2a63f-37cc-4fa3-a895-38a4213740cf.png)

The GLM and FarmCPU results from running each method separately are similar to the ones where GLM precedes FarmCPU.

**Comment by jiabowang** [comment]
Hi,
Thanks for your using GAPIT and sharing this error.
Now we have fixed it.
Please resource GAPIT function and do the analysis again.

Sincerely,
