### ISSUE TITLE
How to obtain text format of Neighbor-Joining (NJ)-tree using GAPIT?

### ISSUE THREAD

**Issue by CXX33** [jiabowang/GAPIT3#24]
Dear all,
I have a question,
I have the honour to read the manual of GAPIT, and interesting to the function of NJ-tree. After testing my data by using parameter with : res_gapit <- GAPIT(Y=myY, GD=myGD, GM=myGM,Inter.Plot=T, NJtree.group = 4), I obtained the NJ-tree only figure. However, I can not edit the tree using other software without text format of NJ-tree.
Should I add some parameter? How can I do it?

Thanks.

**Comment by CXX33** [comment]
Dear all,
   I have a question,
   I have the honour to read the manual of GAPIT, and  interesting to the function of NJ-tree. However, after testing my data by using parameter with :  **res_gapit <- GAPIT(Y=myY, GD=myGD, GM=myGM,Inter.Plot=T)**, I obtained many results with NJ-tree.
  Should I add some parameter or input files? 

Thanks.

**Comment by CXX33** [comment]
The figure of GAPIT manual as follows:
![图片](https://user-images.githubusercontent.com/62325641/130305828-fb77a433-fb04-480f-9401-e494dba13b78.png)

**Comment by jiabowang** [comment]
Hi,

We have no this output in the GAPIT. Sorry.
Maybe we can add this function soon.
Jiabo

**Comment by knausb** [comment]
Hi @CXX33 ,

the function `GAPIT.Genotype()` is called from `GAPIT()`. The function `GAPIT.Genotype()` calculates the kinship matrix (KI) for you and returns it. This is saved as the file 'GAPIT.Kin.VanRaden.csv'. Note that this does not appear to be a 'typical' base R matrix because the first column contains row names and should be omitted if you'd like to treat it as a matrix. I see a tree as a way of visualizing a matrix of data. This can be accomplished as follows (based on the `GAPIT.Genotype()` code).

```
myPhenoFile <- system.file("extdata", "mdp_traits.txt.gz",
                    package = "GAPIT3documentation")
myGenoFile <- system.file("extdata",
                          "mdp_genotype_test.hmp.txt.gz",
                          package = "GAPIT3documentation")

myPhenotypes <- read.table(myPhenoFile, header = TRUE)
myGenotypes  <- read.table(myGenoFile, header = FALSE)

library(GAPIT3)

myGAPIT <- GAPIT(
  Y=myPhenotypes[, 1:2],
  G=myGenotypes,
  PCA.total=3
)

theKin <- as.matrix(myGAPIT$KI[,-1])
distance.matrix <- dist(theKin, upper = TRUE)
hc <- hclust(distance.matrix) #, method = kinship.cluster)
hc <- ape::as.phylo(hc)
plot(hc, type = "fan")

# Uncomment below to write to file.
# ape::write.tree(hc, file = "my_tree.phy")
```

Please take a look and let us know if this is what you were looking for? Thanks!

**Comment by CXX33** [comment]
> 
> 
> Hi @CXX33 ,
> 
> the function `GAPIT.Genotype()` is called from `GAPIT()`. The function `GAPIT.Genotype()` calculates the kinship matrix (KI) for you and returns it. This is saved as the file 'GAPIT.Kin.VanRaden.csv'. Note that this does not appear to be a 'typical' base R matrix because the first column contains row names and should be omitted if you'd like to treat it as a matrix. I see a tree as a way of visualizing a matrix of data. This can be accomplished as follows (based on the `GAPIT.Genotype()` code).
> 
> ```
> myPhenoFile <- system.file("extdata", "mdp_traits.txt.gz",
>                     package = "GAPIT3documentation")
> myGenoFile <- system.file("extdata",
>                           "mdp_genotype_test.hmp.txt.gz",
>                           package = "GAPIT3documentation")
> 
> myPhenotypes <- read.table(myPhenoFile, header = TRUE)
> myGenotypes  <- read.table(myGenoFile, header = FALSE)
> 
> library(GAPIT3)
> 
> myGAPIT <- GAPIT(
>   Y=myPhenotypes[, 1:2],
>   G=myGenotypes,
>   PCA.total=3
> )
> 
> theKin <- as.matrix(myGAPIT$KI[,-1])
> distance.matrix <- dist(theKin, upper = TRUE)
> hc <- hclust(distance.matrix) #, method = kinship.cluster)
> hc <- ape::as.phylo(hc)
> plot(hc, type = "fan")
> 
> # Uncomment below to write to file.
> # ape::write.tree(hc, file = "my_tree.phy")
> ```
> 
> Please take a look and let us know if this is what you were looking for? Thanks!
Professor  knausb: 
    Sorry for my late reply.
    According to your detailed guidance, I can produce a tree file of an editable format!

Thanks for your codes, Best!

**Comment by CXX33** [comment]
Professor @knausb :
    Sorry for my late reply.
    According to your detailed guidance, I can produce a tree file of an editable format!

    Thanks for your codes, Best!

**Comment by knausb** [comment]
Thank you @CXX33 for replying to let us know if the proposed solution worked for you or if it required modification. I feel this is a good way to close an issue. Thanks!
