### ISSUE TITLE
How to use gapit to perform FaST-LMM exactly, NOT SUPER?

### ISSUE THREAD

**Issue by xiekunwhy** [jiabowang/GAPIT3#3]
Hi,
I want to know how to use GAPIT3 to run FaST-LMM model, NOT SUPER.
By the way, is model = "MLM" perform model which implemented in EMMAX program exactly?
Kun.

**Comment by jiabowang** [comment]
Hi,
GAPIT3 did not support to run FaST-LMM directly.
"MLM" mean P3D method for Mixed Linear Model.

**Comment by jiabowang** [comment]
> Hi,
> I want to know how to use GAPIT3 to run FaST-LMM model, NOT SUPER.
> By the way, is model = "MLM" perform model which implemented in EMMAX program exactly?
> Kun.

Hi,
GAPIT3 did not support to run FaST-LMM directly.
"MLM" mean P3D method for Mixed Linear Model.
