### ISSUE TITLE
Phenotypic adjustment prior to GWAS

### ISSUE THREAD

**Issue by ehsankhajouei** [jiabowang/GAPIT3#32]
Hello Jiabo (@jiabowang) and Brian (@knausb),

I have a general question regarding best practice in GAPIT; I have phenotypic and genomic data on replicates of spring wheat. I tried different GWAS scenarios such as calculating BLUPs and running GWAS afterwards, or calculating BLUEs before GWAS analysis, or running GWAS on raw means of replicates per accession, and GWAS with intact data, i.e. using replicated data for GWAS. 

For each of this scenarios I received results and in some cases they overlap. GAPIT produced and estimated BLUP and BLUE for the tested trait in all of these analyses. However, I was wondering what is the best practice that you recommend for adjusting phenotypes prior to GWAS in GAPIT given that you know what is going on under the hood? Many thanks in advance for your time and attention. Best /Ehsan

**Comment by jiabowang** [comment]
Hi @ehsankhajouei,
As we know, GWAS is used to detect association markers with interesting traits.
If there are high heritability and enough effective population size of the interesting traits, the association marker will be easily and credibly detected. So some researchers presented using BLUP or BLUE value as phenotype value in the GWAS. This way could increase the heritability of the arm traits. But some original traits with high heritability do not need to be converted.
Some outlier values in the traits should be removed before GWAS.
The distribution of phenotype values should be addressed also.
Hope that will help with your problem.
Sincerely,
