### ISSUE TITLE
maxLoop parameter of the BLINK model

### ISSUE THREAD

**Issue by baoxingsong** [jiabowang/GAPIT3#35]
Hi Jiabo,

I am interested in how to design novel approaches for genotype encoding. There is much higher LD in my genotypic data than usually used SNPs. As far as I could understand, I need to adjust the maxLoop parameter for the Blink model.

What is the default value of the maxLoop parameter for the Blink model implemented in the GAPIT3 package, please?
How could I change that?

I learned the maxLoop parameter from https://github.com/YaoZhou89/BLINK/blob/master/man/User%20Manual.md

Baoxing from the Buckler Lab at Cornell

**Comment by knausb** [comment]
Hi @baoxingsong 

I see the following.

```
GAPIT3$ grep "maxLoop" R/GAPIT.Blink.R 
`Blink` <- function(Y=NULL,QTN.position=NULL,GD=NULL,GM=NULL,CV=NULL,DPP=100000000,kinship.algorithm="FARM-CPU",file.output=TRUE,cutOff=0.01,method.GLM="FarmCPU.LM",Prior=NULL,ncpus=1,maxLoop=10,LD=0.7,threshold.output=.0001,alpha=c(.01,.05,.1,.2,.3,.4,.5,.6,.7,.8,.9,1),WS=c(1e0,1e3,1e4,1e5,1e6,1e7),GP=NULL,FDRcut=FALSE
```

The `maxLoop` parameter appears in the function definition for `Blink()` and it's default value is 10. This suggests that whatever function you are calling this from should be able to include the parameter `maxLoop=4` where 4 is your desired maxLoop parameterization (change 4 to whatever reasonable number you desire). Hope that helps.

Thanks!
Brian

**Comment by baoxingsong** [comment]
Thanks @knausb.
I tried `myGAPIT <- GAPIT( Y=myY,  GD=myGD,  GM=myGM, CV=myCV, maxLoop=40, model="Blink")`.
But looks like `maxLoop=40` was not working. The log file and the results indicate GAPIT was still running for 10 Iterations.
