### ISSUE TITLE
SNP genotype for GAPIT

### ISSUE THREAD

**Issue by Chenxinxiu** [jiabowang/GAPIT3#36]
Dear Professor:
   I producted a few of  snp genotype data with numeric value **between**  “0” and “2”. I noticed that GAPIT support  this numeric format to used for GWAS. 
![图片](https://user-images.githubusercontent.com/57703882/145134675-b1bd7a84-9666-408a-85f5-26fa7d9bd88f.png)
  However, I have no idear to their working  mechanism. Maybe change the numeric format between  “0” and “2” to "0" "1" "2" ?  If so, how can I get the transformed file? I want to understand it, important to me.
  Best.

**Comment by jiabowang** [comment]
That is used to indicate gene expression levels. And to avoid the coefficient of inbreeding much more than practical, the values should be limited from 0 to 2.
