### ISSUE TITLE
Memory performance

### ISSUE THREAD

**Issue by nhartwic** [jiabowang/GAPIT3#38]
I've been playing around with GAPIT for doing GWAS analysis in soy. In total, I have a hapmap file (or vcf) with about 5.4 million loci and about 1200 samples. I've been encountering significant memory limits with GAPIT.

I haven't fully explored resource usage yet but a run with only a subset of about 100K loci and SNP.fraction set to 0.1 still took about 100 gigs of memory. See linked plots for detailed resource usage in that run...

https://salk-tm-logs.s3.amazonaws.com/CdkBqQYga1NR.metrics/metrics.html

...I have the following questions...

1. Is this resource usage typical? Is there any information on typical resource usage?
2. Is there something I can meaningfully do to reduce memory usage in order to get GAPIT to run successfully on the full 5 million loci (or at least an intelligently selected set that hits all significant linked blocks in the genome)

**Comment by knausb** [comment]
Hi @nhartwic ,

I've tried to document how R uses RAM at the below link.

https://knausb.github.io/vcfR_documentation/how_much_memory.html

My interpretation is that you have a rather large number of samples and loci. This is not really a GAPIT or an R issue. You probably have more data than you have physical RAM. 

GAPIT implements a method to use multiple genotype files. I have no experience with it, but it sounds like what you need. This is documented it section "5.4 Multiple Genotype File".

https://zzlab.net/GAPIT/gapit_help_document.pdf

There may be other strategies to analyze your data, but they will all involve subsetting your data so that you can fit it into existing RAM. This might be considered an 'advanced topic' though.

Also, if you're starting with VCF data, I now have `vcfR::vcfR2hapmap()`. It's not on the CRAN version now, but I can make it available if you're interested.

Good luck!
Brian

**Comment by nhartwic** [comment]
> My interpretation is that you have a rather large number of samples and loci. This is not really a GAPIT or an R issue. You probably have more data than you have physical RAM.

To be clear, loading the variants consumes on the order of 50 gigs of memory. I've never been able to get GAPIT to run on that full dataset. Running on as few as 100K loci still consumed around 110 gigs of memory usage at peak. Of that, under a gig would have been occupied by the variants themselves. This implies GAPIT requires over 100x memory usage relative to the size of the variants table. This seems like a GAPIT issue or an issue with my setup. I'm not deeply familiar with its algorithms, but none of them that I'm aware of should scale this poorly.

> GAPIT implements a method to use multiple genotype files. I have no experience with it, but it sounds like what you need. This is documented it section "5.4 Multiple Genotype File".

Thanks for the suggestion. I'll try to get that system working I guess. Even if I do subset down to chromosomes, that would still be on the order of 500K loci per file which, based on my current runs, seems like it would require on the order of 500 gigs of memory to run. 

> There may be other strategies to analyze your data, but they will all involve subsetting your data so that you can fit it into existing RAM. This might be considered an 'advanced topic' though.

I'm open to suggestions here. 

> Also, if you're starting with VCF data, I now have vcfR::vcfR2hapmap(). It's not on the CRAN version now, but I can make it available if you're interested.

Thanks for the offer. At the moment I'm using Tassel to convert from vcf to hapmap and this seems to be working smoothly. In the event I encounter any difficulties, I'll look into your R based sollution.

**Comment by knausb** [comment]
I see the following.
```
> library(memuse)
> howbig(nrow=5.4e6, ncol=1200, unit="GB")@size
[1] 51.84
```

This appears consistent with your report of the variants requiring 50 Gb. GAPIT tries to maintain the data in a hapmap format as well as a 'numeric' format. I think this means it has a copy of the data matrix which is my guess as to why you saw 100 Gb used. I'm working with the developers to try to address this sort of thing. But that's more of a long term goal. That you saw the same behavior with 100k variants sounds odd though. I'm currently working with a data set of 288 samples and ~250k variants. I work on this on my desktop at home and it's just fine. So I'm not sure what to say there. Did you start a new environment with the smaller data?

On the multiple file note, GAPIT() has a parameter `file.fragment = 99999`. I think this will allow you to read in parts of files. Again, I haven't tried that one, but it sounds like it might help.

**Comment by knausb** [comment]
On other strategies to analyze your data. First, if you really need performance there is plink. It's compiled C, so it should outperform any R solution. Within R I usually look at things as how to reduce the size of the data matrix. Can we reduce the number of rows or columns? If you have 5.4 million loci in a 1 Gbp genome I think you have a variant every 200 bp or so. Markers that close together are likely to be linked and therefore correlated. I'm going to guess that you don't need that many. Perhaps you could thin the number of variants to something that occupies RAM more comfortably? Why do you have so many samples? Are you looking for loci that are significant but small effect so you're looking for high statistical power? If these are siblings can you thin the dataset. You could cluster the samples to get a reduced number of samp[les the represents the diversity in the full data set. Or you could try the CMLM method, which clusters the samples for you. Perhaps some of these ideas may help?
