### ISSUE TITLE
the error i find during run code in the gapit_help_document

### ISSUE THREAD

**Issue by chailixuan** [jiabowang/GAPIT3#39]
the basic command just can not work well...
Based on the GAPIT_Tutorial_Data(https://zzlab.net/GAPIT/)...

such as ...

#Tutorial Step(g-1): Compare to Power against FDR for GLM,MLM,CMLM,ECMLM,SUPER
#Hint:Program runing time is more than 24 hours for repetition 100 times.
#----------------------------------------------------------------------------------------
#Step 1: Set data directory and import files
```
myGD <-read.table("mdp_numeric.txt", head = TRUE)
myGM <-read.table("mdp_SNP_information.txt", head = TRUE)
myKI <- read.table("KSN.txt", head = FALSE)
myG <- read.table("mdp_genotype_test.hmp.txt", head = FALSE)
#Step 2: Run GAPIT
GAPIT.Power.compare(
G=myG,
GD=myGD,
GM=myGM,
KI=myKI,
**nrep**=3, 
h2=0.9,
NQTN=5
)
```

![image](https://user-images.githubusercontent.com/37284630/159708262-2d5af0fb-6106-4e15-9246-772c75d5ce6a.png)

**Comment by jiabowang** [comment]
Hi，
We have re-written the GAPIT help document.
Please reference the newest document.
