### ISSUE TITLE
file.output error and no GWAS output

### ISSUE THREAD

**Issue by yenon118** [jiabowang/GAPIT3#4]
Hi,

I am trying to integrate GAPIT3 to my GWAS1001 project. However, if I set file.output = T, I will get an error saying that the dimension not equal to array extent when it is trying to plot the kinship graph. Therefore, I changed it to file.output = FALSE so that my code wouldn't break. Could you please give me some suggestion to solve this? I need to keep all the output.

![image](https://user-images.githubusercontent.com/22091525/54958489-c8a1b000-4f23-11e9-9107-a75649e35eae.png)

Pictures below are the configurations of GWAS1001. I used the same configuration before when I made the GWAS_Cli_App. However, it doesn't output the GWAS table at the end, and I couldn't figure out why. Could you please give me some suggestion to solve this? 

![image](https://user-images.githubusercontent.com/22091525/54958294-3e594c00-4f23-11e9-9ef4-3fa045a5e051.png)

![image](https://user-images.githubusercontent.com/22091525/54958917-73ff3480-4f25-11e9-8a2f-dd10b04d1d08.png)

![image](https://user-images.githubusercontent.com/22091525/54958323-54ffa300-4f23-11e9-8a3f-797fb8afcb2e.png)

**Comment by jiabowang** [comment]
Hi there,
I noticed that the error is caused by the kinship plotting. There is something wrong with your kinship. But I noticed that you choose GLM. Could you give me more details about your codes?

**Comment by yenon118** [comment]
Hello,

In the GWAS1001 package, there is a .yaml file which is for user to specify the path of their data. After filling the .yaml file, user can run 

> Rscript GWAS1001.R `yaml_file`.yaml -GAPIT 

to start the program. The program will read data based on the path specified in `yaml_file`.yaml. For those which are not specified, they will automatically become NULL or 0. After that, the program will recognized the -GAPIT argument and run GAPIT which was built by you. 

In the `yaml_file`.yaml, I have a kinship matrix, covariates data, and a few separate genotype data and genotype map files. The kinship matrix looks like this after it was read into R environment.
![image](https://user-images.githubusercontent.com/22091525/55112433-953d5d80-50aa-11e9-9f56-19defd6facd0.png)
The covariates data looks like this after it was read into R environment.
![image](https://user-images.githubusercontent.com/22091525/55112516-c1f17500-50aa-11e9-9695-0ce41a16f635.png)

In the past when I built GWAS_Cli_App, I integrated gapit_functions_20160415.txt (this might be GAPIT1 or GAPIT2) written by members of Zhiwu Zhang Lab to my GWAS_Cli_App, and both the kinship matrix and the covariates data works well with the GAPIT function. Since you are building GAPIT3, we hope that we can integrate GAPIT3 into our new GWAS1001.

**Comment by jiabowang** [comment]
Hi, 
From your dataset, I noticed that the first row is not the name of the individual. So the dimension fo the kinship will not match GAPIT format. That is the reason for the error.
Please check the code of reading kinship, and make sure the dimension of the kinship is n by n+1 (n is the number of individuals, and 1 is the name column of individuals).
I am glad to see you integrate GAPIT into your program. Input files and input codes are the same as the previous version.

**Comment by yenon118** [comment]
Hello,

I have fixed the kinship matrix. The dimension of the kinship matrix is n by n+1 now, and it can plot the kinship graph. However, it still doesn't output GWAS results when I run GAPIT with GLM model. Could you please give me some suggestion to solve this?

The parameter for GAPIT include KI, CV, file.Ext.GD, file.Ext.GM, file.GD, file.GM, file.path, file.from, file.to, and model = "GLM", and PCA.total = 0.

The output looks like the pictures below.

<img width="822" alt="Untitled1" src="https://user-images.githubusercontent.com/22091525/55272867-7ea52b00-5291-11e9-9a33-8a5c578bbfd5.png">

<img width="825" alt="Untitled2" src="https://user-images.githubusercontent.com/22091525/55272869-8238b200-5291-11e9-88d3-df928ac24215.png">

**Comment by jiabowang** [comment]
That seems like you did not give a phenotype file. If so, the GAPIT will only do Genomic Prediction progress.

**Comment by yenon118** [comment]
Hi,

I did provide a phenotype file. I tested it again with the exact same configuration but with the older version of GAPIT (gapit_functions_20160415.txt) and it worked. It outputted all the GWAS results. I am wondering if there is a bug in the latest version of GAPIT causing it not output the GWAS results when I use parameters KI, CV, GD, GM, model = GLM, and PCA.total = 0?

Thank you.
