### ISSUE TITLE
Error with a specific covariate

### ISSUE THREAD

**Issue by jorgemasgomez** [jiabowang/GAPIT3#40]
Hi!
I´m trying to perform a GWAS MLM analysis using GAPIT, but I get an error when I use a specific covariate (structure K=6) in the MLM approach. This is curious because I am able to perform it with any other structure covariate (K=3,4,5,7,8..) but not with K=6. Even I obtained succesful results using K=6 with BLINK and FarmCPU approaches. 

The error that I obtain is: 

**"Error in t(KWO) %*% MASS::ginv(as.matrix(KW)) %*% UW : requires numeric/complex matrix/vector arguments
In addition: Warning message: In order(as.numeric(as.character(chor_taxa))) : NAs introduced by coercion
Error in t(KWO) %*% MASS::ginv(as.matrix(KW)) %*% UW : requires numeric/complex matrix/vector arguments"**

I don´t know if it could be related with this frequent question of the manual:

_"11. How to fix the error of using covariates from STRUCTURE as fixed effects?
A: This error is occurring because the covariates from STRUCTURE are linearly dependent. In particular, for a given individual/taxa, these covariates sum to 1. To circumvent this error, remove one of the STRUCTURE covariates from the corresponding input file."_

But in any case I´m not able of how to interpret this to solve it.

Some solution?

Thanks in advance!!!!

**Comment by jiabowang** [comment]
Hi, The Q matrix should be removed one column as covariance in the GAPIT.
