### ISSUE TITLE
Error in apply(X, 2, max) : dim(X)的值必需是正数 In addition: Warning message: In order(as.numeric(as.character(chor_taxa))) :  Error in apply(X, 2, max) dim(X) must have a positive length when applying function in data frame

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [jiabowang/GAPIT3#41]
when I run the gapit,the error 
my friend, how to debug this error. thanks

**Comment by jiabowang** [comment]
I guess there may be other characters in your numeric genotype file (myGD).
In that file, all elements should be numeric values.
