### ISSUE TITLE
Error with user provided kinship

### ISSUE THREAD

**Issue by lurens** [jiabowang/GAPIT3#42]
Hi
I am trying to running GAPIT with a kinship matrix already generated
However i got this error message
Error in if (KI != 1) { : the condition has length > 1
In addition: Warning messages:
1: 'memory.size()' is no longer supported 
2: 'memory.size()' is no longer supported 
3: 'memory.size()' is no longer supported 
 Error in if (KI != 1) { : the condition has length > 1

Any idea?
Thank you

**Comment by jiabowang** [comment]
Hi,
That should be a BUG. I will fix that error.
When I finished, will tell you.

thanks,

**Comment by jiabowang** [comment]
This BUG has been fixed.
