### ISSUE TITLE
manhattan plot does not plot all chromosomes

### ISSUE THREAD

**Issue by kostasgalexiou** [jiabowang/GAPIT3#45]
Hi,

I am running GAPIT3 using the following command

```
Rscript ../GAPIT.R \
ploidy4_12scaffolds_diploid_SNPs_atLeast1Trait_filt.hmp \
pheno_MD_166.txt \
covariates_166indvs.txt k\
inship_166indvs.txt \
3 \  # number of PCs used
166  # number of samples
```

Even though the program runs properly, for some reason, it does not plot markers lying in the Iast 4 chromosomes (*Genomewise.pdf) but it does generate the individual plots for all the chromosomes (*Chromosomewise.pdf). I have attached the corresponding files in order to reproduce the error.

[ploidy4_12scaffolds_diploid_SNPs_atLeast1Trait_filt.hmp.txt](https://github.com/jiabowang/GAPIT3/files/8948086/ploidy4_12scaffolds_diploid_SNPs_atLeast1Trait_filt.hmp.txt)
[GAPIT.R.txt](https://github.com/jiabowang/GAPIT3/files/8948097/GAPIT.R.txt)  # need to modify line 12
[covariates_166indvs.txt](https://github.com/jiabowang/GAPIT3/files/8948099/covariates_166indvs.txt)
[kinship_166indvs.txt](https://github.com/jiabowang/GAPIT3/files/8948100/kinship_166indvs.txt)
[pheno_MD_166.txt](https://github.com/jiabowang/GAPIT3/files/8948101/pheno_MD_166.txt)
.
Thanks

**Comment by jiabowang** [comment]
Now this error has been fixed.
