### ISSUE TITLE
Error in GWAS analysis with multiple traits and multiple model

### ISSUE THREAD

**Issue by akhtarmzn2010** [jiabowang/GAPIT3#46]
I am running GAPIT3 using the following command for GWAS analysis:

for(i in 2:ncol(myY))
{
myGAPIT <- GAPIT(
Y=myY[,c(1,i)],
GD=myGD,
GM=myGM,
model=c("GLM","MLM","MLMM","FarmCPU","Blink"), 
PCA.total=3,                                           
NJtree.group=4,                              
Geno.View.output=F,
Inter.Plot=FALSE,                                       
Multiple_analysis=TRUE,                               
PCA.3d=FALSE,                                          
file.output=T
)
}

# i got this error message

Error in if (file.output & !SNP.test & model_store %in% c("gBLUP", "cBLUP",  : 
  the condition has length > 1
In addition: Warning message:
In max(numeric.chr, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf

**Comment by xibeixingchen** [comment]
You don't need to cycle every trait, just Y = myY

**Comment by jiabowang** [comment]
This error has been fixed.

**Comment by akhtarmzn2010** [comment]
Thank you very much sir.
