### ISSUE TITLE
Error in La.svd

### ISSUE THREAD

**Issue by xf78** [jiabowang/GAPIT3#50]
GAPIT3 is a great tool, but there was an error in my data, and I don't know why the error was reported，Looking forward to the developer's reply！ thanks
![image](https://user-images.githubusercontent.com/13416926/192481605-38cdb490-a780-4364-92d0-a21af5670d6f.png)

**Comment by xf78** [comment]
additional，I have checked my unbuntu system，libblas.so and liblapack.so have locate in ：/usr/lib/x86_64-linux-gnu
![image](https://user-images.githubusercontent.com/13416926/192485372-32e2a969-4269-4046-9aa1-50d5b6b44550.png)

**Comment by jiabowang** [comment]
Hello,
This error seems to be caused by stats::prcomp function.
Please check this function in your R.

Sincerely,


Jiabo

**Comment by xf78** [comment]
thanks，this problem is indeed caused by stats::prcomp, when test code in radian console , stats::prcomp does have this error,should test this code in pristine R console or Rstudio.
