### ISSUE TITLE
object 'lettet.index' not found

### ISSUE THREAD

**Issue by batteryis** [jiabowang/GAPIT3#51]
Hi, I have ran GAPIT and it ran perfectly good and produce results before this, until yesterday. But today, I got this error msg while performing all my GAPIT GWAS analysis;

Error in GAPIT.Genotype(G = G, GD = GD, GM = GM, KI = KI, PCA.total = PCA.total,  :
  object 'lettet.index' not found

I have tried to reinstalled GAPIT, tried with samples that ran perfectly before but the same error occurred. Appreciate if you can help me on this. 

Thank you
![gapit_error](https://user-images.githubusercontent.com/114970102/193725917-64cf4bc2-768f-4751-b452-e28ceccb7d67.PNG)

**Comment by jiabowang** [comment]
Thank you. We have revised this error.
