### ISSUE TITLE
Error in Multi-traits and Multi-model GWAS

### ISSUE THREAD

**Issue by akhtarmzn2010** [jiabowang/GAPIT3#53]
Hi,
I am running multiple model GWAS with multi traits phenotype. Following script I used:

myGAPIT <- GAPIT(
Y=myY,
GD=myGD,
GM=myGM,
PCA.total=3,
NJtree.group=3,
Multiple_analysis=TRUE,
model=c("GLM","MLM","MLMM","FarmCPU","Blink")
)

Following error i was found:
----------------------------------------------------------------
Error in `[.data.frame`(geneGD, GT %in% taxa_Y) : 
  undefined columns selected
In addition: There were 50 or more warnings (use warnings() to see the first 50)
---------------------------------------------------------------

I have another issue in Multi-model run, when I using multi-traits data, it started with GLM first for all traits. If any error found in anyone traits, run was stooped and I have to repeat run for all traits and multiple model.
Can we I run multiple model with traits wise (first run all model for first trait with Multiple_analysis=TRUE, and then run for second trait) ?

Please help me to solve this issues.

Best Regards,
Javed Akhatar

**Comment by jiabowang** [comment]
Hi Javed,

From your report, I suggest you check the taxa of individuals in the genotype file and phenotype file.
As for your suggestion, we can not implement it. You can set loops for different traits with multiple models.

**Comment by akhtarmzn2010** [comment]
Hi,

Thank you for the suggestion, can you please write the command for loops?

myGAPIT <- GAPIT(
Y=myY,
GD=myGD,
GM=myGM,
PCA.total=3,
NJtree.group=3,
Multiple_analysis=TRUE,
model=c("GLM","MLM","MLMM","FarmCPU","Blink")
)
How can I edit this command for loop run.

Thanks
Javed

**Comment by akhtarmzn2010** [comment]
Dear  Sir, 
I have another issue in updated R function. This function can not generate multiple-QQ plot and Multiple-manhattan plot separate for each traits. Please add "traits name" in the file name of multiple-QQ plot and Multiple-manhattan plot, So plot can generate separately for each trait:

for(i in 2:ncol(myY))
{
myGAPIT <- GAPIT(
Y=myY[,c(1,i)],
GD=myGD,
GM=myGM,
KI=myKI,
CV=myCV,
Phenotype.View= FALSE,
Geno.View.output = FALSE,
Random.model=FALSE,
NJtree.group=3,
model=c("GLM","MLM","MLMM","FarmCPU","Blink"),
Inter.Plot=FALSE,
Multiple_analysis=TRUE,
file.output=T
)
}

Some time run stopped with "MLMM" or "FarmCPU" or "Blink" model and show error"

step  3  done! pseudo-h= NaN 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'a' in selecting a method for function 'solve': the leading minor of order 1 is not positive definite

Please correct al these bugs in updated function.

Best wishes
Javed

**Comment by jiabowang** [comment]
Hi Javed,

We can not add "trait name" to the output file name. Because other researchers just use this function to analyze with multiple traits or multiple methods.
From your report, the error is caused by the estimation of heritability in the MLM. This may be caused by the selected kinship. In the MLMM, we suggest the kinship built by GAPIT default.


Sincerely,

Jiabo

**Comment by akhtarmzn2010** [comment]
Hi Jiabo,

Can you share with me a code for create multiple Manhattan plot for different model in single trait by GWAS result file.

Best Wishes
Javed

**Comment by jiabowang** [comment]
@akhtarmzn2010 

GMM=GAPIT.Multiple.Manhattan(model_store=c("GLM","MLM","FarmCPU","Blink"),Y.names="traitname",cutOff=0.01,GM=myGM)

**Comment by akhtarmzn2010** [comment]
Thank you very much...
