### ISSUE TITLE
Error in "MLMM model" 

### ISSUE THREAD

**Issue by akhtarmzn2010** [jiabowang/GAPIT3#56]
Hi Jiabo,
Can you please resolve this error in new update, because most of the trait shows this error in "MLMM model" so many times when I use "Multiple_analysis=TRUE". I am stuck on GWAS analysis as I have too many traits with multiple data sets.
------------------------------------------------------------
Error 1:
[1] "GWAS by MLMM method !!"
[1] "The Kinship is provided by user !!"
null model done! pseudo-h= 0.378 
step 1 done! pseudo-h= 0.298 
step  2  done! pseudo-h= 0.221 
step  3  done! pseudo-h= 0.177 
step  4  done! pseudo-h= 0.126 
step  5  done! pseudo-h= 0.017 
step  6  done! pseudo-h= 0 
step  7  done! pseudo-h= 0 
backward analysis 
creating output 
Error in `[.data.frame`(GWAS_result, , c(1, 3)) : 
  undefined columns selected
-----------------------------------------------------------
Error 2:
[1] "GWAS by MLMM method !!"
[1] "The Kinship is provided by user !!"
null model done! pseudo-h= 0.638 
step 1 done! pseudo-h= 0.683 
step  2  done! pseudo-h= 0.683 
step  3  done! pseudo-h= 0.738 
step  4  done! pseudo-h= 0.809 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'a' in selecting a method for function 'solve': the leading minor of order 267 is not positive definite
In addition: Warning messages:
1: In rm(eig.L) : object 'eig.L' not found
2: In merge.data.frame(gs.blup, BLUE, by.x = "Taxa", by.y = "Taxa") :
  column names ‘NA’, ‘NA’ are duplicated in the result
3: In log(Lambdas) : NaNs produced
4: In log(Lambdas) : NaNs produced
5: In log(Lambdas) : NaNs produced
6: In log(Lambdas) : NaNs produced
7: In log(Lambdas) : NaNs produced
8: In log(Lambdas) : NaNs produced
----------------------------------------------------------------
Please help me..

Best wishes
Javed

**Comment by jiabowang** [comment]
@akhtarmzn2010 
Hi Javed,

Did you use the newest GAPIT function?
Recently, I added some codes to output GWAS marker effect.
I think that works.
If you have tested with the newest function and the error is still there.

Please share your data with me, so I can figure out what is the reason.


Sincerely,


Jiabo

**Comment by akhtarmzn2010** [comment]
<div class="aju"><div class="aCi"><img id=":17l_17-e" name=":17l" src="https://lh3.googleusercontent.com/a/ALm5wu2r0Nqx8B_kAdLXbBrpsHoUZ4yW2TDIWpA4vHngmw=s40-p" class="ajn" style="background-color: #a4c2f4" jid="akhtarmzn2010@gmail.com" data-hovercard-id="akhtarmzn2010@gmail.com" data-name="Javed Akhatar" aria-hidden="true"></div></div><div class="gs"><div class="gE iv gt">

Javed Akhatar <akhtarmzn2010@gmail.com> | Javed Akhatar <akhtarmzn2010@gmail.com> | 4:03 PM (1 minute ago)
-- | -- | --
Javed Akhatar <akhtarmzn2010@gmail.com>

Javed Akhatar <akhtarmzn2010@gmail.com>
	
Attachments4:03 PM (1 minute ago)
	
to jiabowang/GAPIT3, jiabowang/GAPIT3, Mention
Hi Jaibo,

Yes, I am using newest GAPIT function and still getting errors and some missing files (Multiple Manhattan and QQ plot for each traits separately)
Most frequent errors getting in MLMM model with "Multiple_analysis=TRUE". 
I have a large file size,  > 3 lac SNPs data set of 289 genotypes. Server send  me the response as file size is too large.
[The response from the remote server was: 552 5.3.4 Message size exceeds fixed limit .]
I need to generate a "GAPIT.Association.Manhattans_Symphysic.pdf" file for each trait from GWAS output files, please share commands for that.

Again Error:
--------------------------
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'a' in selecting a method for function 'solve': the leading minor of order 170 is not positive definite
---------------------------
Please help me.

Best Regards
Javed

**Comment by jiabowang** [comment]
Hi Javed,

Please print more details about this error.


Sincerely,

Jiabo

akhtarmzn2010 ***@***.***> 于2022年11月9日周三 18:37写道：

**Comment by akhtarmzn2010** [comment]
Hi Jaibo,

This is the log details of this error. 

I got different type error massages on MLMM model, as previous issues I posted:
https://github.com/jiabowang/GAPIT3/issues/56#issue-1439475850


[1] "--------------------Processing traits----------------------------------"
[1] "Phenotype provided!"
[1] "The 3 model in all."
[1] "MLMM"
[1] "Processing trait: RFW_Y2"
[1] "--------------------Phenotype and Genotype ----------------------------------"
[1] "MLMM"
[1] "There are  1  traits in phenotype data."
[1] "There are  289  individuals in phenotype data."
[1] "There are  330749  markers in genotype data."
[1] "Phenotype and Genotype are test OK !!"
[1] "--------------------GAPIT Logical ----------------------------------"
[1] "GAPIT.IC in process..."
[1] "There are 289 common individuals in genotype , phenotype and CV files."
[1] "The dimension of total CV is "
[1] 289   4
[1] "GAPIT.IC accomplished successfully for multiple traits. Results are saved"
[1] "GAPIT.SS in process..."
[1] "GWAS by MLMM method !!"
[1] "The Kinship is provided by user !!"
null model done! pseudo-h= 0.361 
step 1 done! pseudo-h= 0.312 
step  2  done! pseudo-h= 0.858 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'a' in selecting a method for function 'solve': the leading minor of order 170 is not positive definite
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Best Regards
Javed

**Comment by jiabowang** [comment]
Hi Javed,

Thanks for your information about the error details.
I noticed that the Kinship used is provided by you.

[image: image.png]

So I think the reason for the error may be here.
Please remove this kinship and GAPIT will calculate it using Zhang method.
This method has been tested by ourselves with MLMM method.

Sincerely,


Jiabo

akhtarmzn2010 ***@***.***> 于2022年11月10日周四 12:13写道：

**Comment by akhtarmzn2010** [comment]
Hi Jaibo,

Thank you for the suggestions.
I remove kinship as you suggested but still i got this another error at MLMM model again. I don't know what happen.
Is there any issue by some missing value (NA) in Phenotypic data?

Your previous version a couple of months ago was working very fine, even with missing values.

[1] "--------------------Processing traits----------------------------------"
[1] "Phenotype provided!"
[1] "The 3 model in all."
[1] "MLMM"
[1] "Processing trait: BL_GT_AT_Y2"
[1] "--------------------Phenotype and Genotype ----------------------------------"
[1] "MLMM"
[1] "There are  1  traits in phenotype data."
[1] "There are  289  individuals in phenotype data."
[1] "There are  330749  markers in genotype data."
[1] "Phenotype and Genotype are test OK !!"
[1] "--------------------GAPIT Logical ----------------------------------"
[1] "GAPIT.IC in process..."
[1] "There are 279 common individuals in genotype , phenotype and CV files."
[1] "The dimension of total CV is "
[1] 279   4
[1] "GAPIT.IC accomplished successfully for multiple traits. Results are saved"
[1] "GAPIT.SS in process..."
[1] "GWAS by MLMM method !!"
[1] "The Kinship is provided by user !!"
null model done! pseudo-h= 0.638 
step 1 done! pseudo-h= 0.683 
step  2  done! pseudo-h= 0.683 
step  3  done! pseudo-h= 0.738 
step  4  done! pseudo-h= 0.809 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'a' in selecting a method for function 'solve': the leading minor of order 267 is not positive definite
In addition: Warning messages:
1: In rm(eig.L) : object 'eig.L' not found
2: In merge.data.frame(gs.blup, BLUE, by.x = "Taxa", by.y = "Taxa") :
  column names ‘NA’, ‘NA’ are duplicated in the result
3: In log(Lambdas) : NaNs produced
4: In log(Lambdas) : NaNs produced
5: In log(Lambdas) : NaNs produced
6: In log(Lambdas) : NaNs produced
7: In log(Lambdas) : NaNs produced
8: In log(Lambdas) : NaNs produced

Please check and help me.

Best Regards
Javed

**Comment by jiabowang** [comment]
No, the kinship still is provided.
[image: image.png]

akhtarmzn2010 ***@***.***> 于2022年11月10日周四 19:06写道：

**Comment by akhtarmzn2010** [comment]
Hi Jaibo,,
 Still getting the same error after removing kinship.

command for GWAS analysis for multiple traits:

for(i in 2:ncol(myY))
{
myGAPIT <- GAPIT(
Y=myY[,c(1,i)],
GD=myGD,
GM=myGM,
Phenotype.View= FALSE,
Geno.View.output = FALSE,
Random.model=FALSE,
NJtree.group=3,
model=c("GLM","MLM","MLMM","FarmCPU","Blink"),
Inter.Plot=FALSE,
Multiple_analysis=TRUE,
file.output=T
)
}

Is there any need to change the command?

Best Regards,
Javed

**Comment by jiabowang** [comment]
I noticed that the estimated h2 in the MLMM is increasing when the
multiple steps going.
That value should be decreasing.
So I guess the MLMM method is not a better method for this data.


akhtarmzn2010 ***@***.***> 于2022年11月11日周五 14:11写道：

**Comment by akhtarmzn2010** [comment]
Hi Jaibo,

Thank you very much to clear the problem with MLMM model, it mean i can't use this model for GWAS.

Can you suggest me which model is best fir for my data set ?
or can I use "GLM","MLM","SUPER","FarmCPU","Blink", these five model ?

I also need to generate a "GAPIT.Association.Manhattans_Symphysic.pdf" file for each trait from GWAS output files, please share commands for that.

Best Regards
Javed

**Comment by jiabowang** [comment]
Hi Javed,

Rest models should be OK for your data.
Now the Manhattans_Symphysic plot has been output by default in the GAPIT.
Of course, that output needs there are several significant markers in GWAS
methods.


Sincerely,

Jiabo

akhtarmzn2010 ***@***.***> 于2022年11月12日周六 16:29写道：

**Comment by akhtarmzn2010** [comment]
Hi Jaibo, 

I am trying to run other models.
If possible, please share command for generate "Manhattans_Symphysic plot" from GWAS output files. This plot is helpful me for interpreting the GWAS results.

Best Regards,
Javed

**Comment by jiabowang** [comment]
Hi Javed,

Multiple_analysis=TRUE
Now, this command is set as default in the GAPIT, so the
Manhattans_Symphysic plot should be outputted for each trait.

Sincerely,

Jiabo

akhtarmzn2010 ***@***.***> 于2022年11月14日周一 15:28写道：
