### ISSUE TITLE
ERROR: dependency 'LDheatmap' is not available for package 'GAPIT3'

### ISSUE THREAD

**Issue by Vinit2401** [jiabowang/GAPIT3#61]
I am trying to install GAPIT3. i tried all the ways but it always ends up in below error
ERROR: dependency 'LDheatmap' is not available for package 'GAPIT3'

Also, LDheatmap cannot be installed. Please help.

**Comment by askruse2** [comment]
Hi! Did you ever solve this error message? I have the same one.

**Comment by jpiaskowski** [comment]
LDheatmap is current not on CRAN, so it needs to be installed from GitHub. This also requires several accessory packages found on Bioconductor: 

1. Install Bioconductor
```
install.packages("BiocManager")
```

2. Install [snpStats](https://www.bioconductor.org/packages/release/bioc/html/snpStats.html) & [multtest](https://www.bioconductor.org/packages/release/bioc/html/multtest.html) from Bioconductor: 
```{r}
BiocManager::install("snpStats")
BiocManager::install("multtest")
```

3. Install [LDheatmap](https://github.com/SFUStatgen/LDheatmap) from GitHub. This requires either the "devtools" or "remotes" packages be installed. 
```{r}
remotes::install_github("SFUStatgen/LDheatmap")
```

4. Install GAPIT

```{r}
remotes::install_github("jiabowangGAPIT", force=TRUE)
library(GAPIT)
```
