### ISSUE TITLE
GAPIT.RandomModel beginning...    take  too  long time

### ISSUE THREAD

**Issue by hewm2008** [jiabowang/GAPIT3#9]
Dear  Author
  Thank you for providing such good software for GWAS analysis . and  I have been using it and it is very good.  However, I recently used the updated version of the gapit_functions and found that some traits have been stuck in this step [RandomModel beginning].   It take too long time at this step at some traits .
Is there anything wrong? I suspect that an endless loop has already taken place at this step for some traits.

**Comment by jiabowang** [comment]
Hi,
Please use Random.model=FALSE to turn off the random model.
